CREATE TABLE USERS
(
    ID SERIAL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    ROLE INT
);

CREATE TABLE ROLES
(
    ID SERIAL,
    NAME VARCHAR(255)
);

INSERT INTO ROLES (ID, NAME) VALUES (1, 'USER');
INSERT INTO ROLES (ID, NAME) VALUES (2, 'ADMIN');

--INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, ROLE) VALUES ('JOHN', 'DOE', 'john.doe@email.com', 'password', 1);