CREATE TABLE ROLES
(
    ID SERIAL NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_ROLE_NAME UNIQUE (NAME)
);

CREATE TABLE STATES
(
    ID SERIAL NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_STATE_NAME UNIQUE (NAME)
);

CREATE TABLE USERS
(
    ID SERIAL NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE INT NOT NULL,
    STATE INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT USER_ROLE FOREIGN KEY (ROLE) REFERENCES ROLES(ID),
    CONSTRAINT USER_STATE FOREIGN KEY (STATE) REFERENCES STATES(ID),
    CONSTRAINT UNIQUE_USER_EMAIL UNIQUE (EMAIL)
);

INSERT INTO ROLES (ID, NAME) VALUES (1, 'USER');
INSERT INTO ROLES (ID, NAME) VALUES (2, 'ADMIN');

INSERT INTO STATES (ID, NAME) VALUES (1, 'PENDING_ACTIVATION');
INSERT INTO STATES (ID, NAME) VALUES (2, 'ACTIVE');
INSERT INTO STATES (ID, NAME) VALUES (3, 'INACTIVE');

INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, ROLE, STATE) VALUES (1, 'FRAN', 'OLEA', 'email@gmail.com', 'password', 2, 2);
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, ROLE, STATE) VALUES (2, 'PANCHO', 'CASTANIAS', 'pancho.castanias@gmail.com', 'password', 1, 1);